name: _cicd (build and release entry)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release-dev:
    if: github.event_name == 'workflow_dispatch'
    uses: i-dot-ai/ai-gov-uk-website/.github/workflows/build-and-release.yml@19d02eb5182badf4ee8539e6b6833ba81b2a5daf
    with:
      environment: dev
      commit_hash: ${{ github.sha }}
      destination_bucket: 'test-ai-gov-uk-website-upload'
    secrets: inherit
      

  release-prod:
    if: github.event_name == 'push' && github.ref_name == 'main'
    uses: i-dot-ai/ai-gov-uk-website/.github/workflows/build-and-release.yml@19d02eb5182badf4ee8539e6b6833ba81b2a5daf
    with:
      environment: prod
      commit_hash: ${{ github.sha }}
      destination_bucket: 'test-ai-gov-uk-website-upload'
    secrets: inherit