name: _cicd (build and release entry)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release-dev:
    if: github.event_name == 'workflow_dispatch'
    uses: i-dot-ai/ai-gov-uk-website/.github/workflows/build-and-release.yml@1225122c64c182bc88f5b035cc08c5704868b4d1
    with:
      environment: dev
      commit_hash: ${{ github.sha }}
      destination_bucket: "DEV_DESTINATION_BUCKET"
    secrets: inherit
      

  release-prod:
    if: github.event_name == 'push' && github.ref_name == 'main'
    uses: i-dot-ai/ai-gov-uk-website/.github/workflows/build-and-release.yml@1225122c64c182bc88f5b035cc08c5704868b4d1
    with:
      environment: prod
      commit_hash: ${{ github.sha }}
      destination_bucket: "PROD_DESTINATION_BUCKET"
    secrets: inherit