name: _cicd (build and release entry)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release-prod:
    if: github.event_name == 'workflow_dispatch'
    uses: i-dot-ai/ai-gov-uk-website/.github/workflows/build-and-release.yml@main
    with:
      environment: prod
      commit_hash: ${{ github.sha }}
      destination_bucket: "PROD_DESTINATION_BUCKET"
    secrets: inherit
      

  release-dev:
    if: github.event_name == 'push' && github.ref_name == 'main'
    uses: i-dot-ai/ai-gov-uk-website/.github/workflows/build-and-release.yml@main
    with:
      environment: dev
      commit_hash: ${{ github.sha }}
      destination_bucket: "DEV_DESTINATION_BUCKET"
    secrets: inherit